# These are supported funding model platforms

github: Droid Burn-orgnasation,DJR07
patreon: Droid Burn
open_collective: Droid Burn
ko_fi: Droid Burn
tidelift: # Droid Burn
community_bridge: Droid Burn
liberapay: Droid Burn
issuehunt: Droid Burn
otechie: Droid Burn
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
